# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: CI Action

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Cache PIO toolchain
      uses: actions/cache@v3
      with:
        key: platformio-toolchain-cache
        path: /home/runner/.platformio

    - name: Build Firmware
      run: |
        pio run -e nrf52840_dk

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: firmware
        path: |
          .pio/build/**/*.config
          .pio/build/**/*.dts
          .pio/build/**/*.elf
